### ISSUE TITLE
Test new version in fractal-containers

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-vizarr-viewer#43]
Refs:
* #42 
* https://github.com/fractal-analytics-platform/fractal-containers/tree/main/examples/full-stack

**Comment by zonia3000** [comment]
Tested with `ghcr.io/fractal-analytics-platform/fractal-vizarr-viewer:dev` and it works as expected. I think that we can regenerate the stable Docker version too.

**Comment by jluethi** [comment]
Is this how we show the errors? If we get those more explicit errors correctly, can we translate them to something users are more likely to understand.

For the 403: Do we know whether the user was logged in without access to that file or just not logged in for that? Can we display corresponding errors with the right hints about what to do?

**Comment by zonia3000** [comment]
> Is this how we show the errors? If we get those more explicit errors correctly, can we translate them to something users are more likely to understand.

The error message is built inside the zarrita.js library.

https://github.com/manzt/zarrita.js/blob/f3f3a196cdc87bc31124b527b133f3f4f90f4f32/packages/storage/src/fetch.ts#L26

The status code is inserted inside the message. This means that when we receive the message in vizarr we have to parse the string to obtain the status code, which is feasible but not very elegant. It would be better to have a custom error class that contains also a status code field.

So, I can add some logic in our fork, but I don't know if that would be merged upstream, since it looks quite related to our specific needs: we can create custom error codes for status that we produce like 500, 404, 401 and 403, but what about all the other possible error codes?

> For the 403: Do we know whether the user was logged in without access to that file or just not logged in for that? Can we display corresponding errors with the right hints about what to do?

The proper way to do this is returning 401 instead of 403 if the user is not logged in. No problem in adding this. It has to be ignored when `AUTHORIZATION_SCHEME` is set to `none`, which is the case where we support anonymous users.

**Comment by zonia3000** [comment]
> Let's start with this update. Likely it will cover the most relevant cases.

Done in #47

**Comment by zonia3000** [comment]
Generated again the docker image `ghcr.io/fractal-analytics-platform/fractal-vizarr-viewer:stable`
